spring:
  profiles:
    include: kafka-config

server:
  context-path: /
  port: 8081

#kafka:
#  enabled: false
#  address: ${service.kafka.url}
#  send_reatempt: 50

logging:
  level:
    root: info