#kafka:
#  bootstrap:
#    servers: http://172.21.185.30:9092
#  topics:
#     server3:
#       some-topic: "server3-some-topic"

kafka:
  topics:
    server3:
      some-topic: "server3-some-topic"

spring:
  kafka:
    bootstrap-servers: http://172.21.185.30:9092
    consumer:
      autoOffsetReset: earliest
      enableAutoCommit: true
      autoCommitInterval: 1000
      properties:
        session.timeout.ms: 35000
