spring:

server:
  context-path: /
  port: 8082

#kafka:
#  enabled: false
#  address: ${service.kafka.url}
#  send_reatempt: 50

logging:
  pattern:
    level: '%5p [${spring.application.name},%X{X-B3-TraceId},%X{X-B3-SpanId},%X{X-Span-Export}]'
  level:
    root: info